/**
 * Reports fixtures — values exactly as drawn in
 * 02_Core_App_Screens/06_Reports.png.
 * DESIGN FIXTURE, not live output. Every string/number on the screen lives
 * here and is rendered in the order listed.
 */
import { C } from "@/components/charts";

/** Colour key shared by tiles, chips and icons. `orange` maps to the
 *  `medium` token; `teal` to `--color-teal`. */
export type Tone = "blue" | "green" | "purple" | "orange" | "red" | "teal" | "grey";

/* ---- Header -------------------------------------------------------- */
export const header = {
  title: "Reports",
  subtitle: "Generate, view and export drilling reports and summaries",
  rigLabel: "OML18-W12",
  rangeLabel: "Apr 20 – May 24, 2025",
  action: "New Report",
};

/* ---- Row 1: KPI cards ---------------------------------------------- */
export const kpis: {
  title: string;
  value: string;
  /** plain grey sub-line (used when there is no delta) */
  sub?: string;
  /** "▲ 18% vs previous 30 days" (green) */
  delta?: { value: string; suffix: string };
  tone: Tone;
  icon: "doc" | "calendar" | "download";
}[] = [
  {
    title: "Reports Generated",
    value: "142",
    delta: { value: "18%", suffix: "vs previous 30 days" },
    tone: "blue",
    icon: "doc",
  },
  {
    title: "Scheduled Reports",
    value: "28",
    sub: "Active automated reports",
    tone: "green",
    icon: "calendar",
  },
  {
    title: "Reports This Period",
    value: "32",
    sub: "Apr 20 – May 24, 2025",
    tone: "orange",
    icon: "doc",
  },
  {
    title: "Downloads",
    value: "96",
    delta: { value: "22%", suffix: "vs previous 30 days" },
    tone: "purple",
    icon: "download",
  },
];

/* ---- Row 2 (left): Report categories ------------------------------- */
export const categories = {
  title: "Report Categories",
  description: "Commonly used report types",
  footer: "View All Report Templates",
};

export type TemplateIcon =
  | "doc"
  | "calendar"
  | "file"
  | "hourglass"
  | "shield"
  | "warning"
  | "dollar"
  | "sliders";

export const templates: {
  name: string;
  description: string;
  frequency: string;
  tone: Tone;
  icon: TemplateIcon;
}[] = [
  {
    name: "Daily Drilling Report",
    description: "Summary of daily operations, KPIs, and events.",
    frequency: "Daily",
    tone: "blue",
    icon: "doc",
  },
  {
    name: "Weekly Summary",
    description: "Weekly performance, NPT, safety and progress.",
    frequency: "Weekly",
    tone: "green",
    icon: "calendar",
  },
  {
    name: "Well Summary Report",
    description: "Comprehensive well performance summary.",
    frequency: "On Demand",
    tone: "purple",
    icon: "file",
  },
  {
    name: "NPT Analysis Report",
    description: "Detailed analysis of non-productive time.",
    frequency: "On Demand",
    tone: "orange",
    icon: "hourglass",
  },
  {
    name: "Safety Report",
    description: "Safety performance, alerts and incidents.",
    frequency: "Weekly",
    tone: "red",
    icon: "shield",
  },
  {
    name: "Incident Report",
    description: "Detailed incident log and analysis.",
    frequency: "On Demand",
    tone: "red",
    icon: "warning",
  },
  {
    name: "Cost Report",
    description: "Drilling cost breakdown and trends.",
    frequency: "Monthly",
    tone: "teal",
    icon: "dollar",
  },
  {
    name: "Custom Report",
    description: "Build a custom report for your needs.",
    frequency: "Custom",
    tone: "grey",
    icon: "sliders",
  },
];

/* ---- Row 2 (right): Reports overview ------------------------------- */
export const overview = {
  title: "Reports Overview",
  rangeValue: "Last 30 Days",
  centerValue: "32",
  centerLabel: "Reports",
  stats: [
    { label: "Most Generated", value: "Daily Drilling Report" },
    { label: "Least Generated", value: "Safety Report" },
    { label: "Avg. Generation Time", value: "2m 34s" },
  ],
};

export const overviewSlices: { label: string; value: number; pct: string; color: string }[] = [
  { label: "Daily Drilling Report", value: 14, pct: "43.8%", color: C.blue },
  { label: "Weekly Summary", value: 6, pct: "18.8%", color: C.green },
  { label: "Well Summary Report", value: 5, pct: "15.6%", color: C.purple },
  { label: "NPT Analysis Report", value: 3, pct: "9.4%", color: C.orange },
  { label: "Safety Report", value: 2, pct: "6.3%", color: C.red },
  { label: "Other", value: 2, pct: "6.3%", color: C.grey },
];

/* ---- Row 3 (left): Recent reports ---------------------------------- */
export const recent = {
  title: "Recent Reports",
  description: "Your recently generated and downloaded reports",
  filterValue: "All Reports",
  searchPlaceholder: "Search reports...",
  columns: [
    "Report Name",
    "Type",
    "Well / Rig",
    "Generated By",
    "Generated On",
    "Period Covered",
    "Format",
    "Size",
    "Actions",
  ],
  footer: "View All Reports",
};

export const recentRows: {
  name: string;
  icon: TemplateIcon;
  type: string;
  tone: Tone;
  wellRig: string;
  generatedBy: string;
  generatedOn: string;
  period: string;
  format: "PDF" | "Excel";
  size: string;
}[] = [
  {
    name: "Daily Drilling Report",
    icon: "doc",
    type: "Daily",
    tone: "blue",
    wellRig: "OML18-W12 / Rig 12",
    generatedBy: "Drilling Engineer",
    generatedOn: "May 24, 2025 07:30 AM",
    period: "May 23, 2025",
    format: "PDF",
    size: "2.4 MB",
  },
  {
    name: "Weekly Summary Report",
    icon: "calendar",
    type: "Weekly",
    tone: "green",
    wellRig: "OML18-W12 / Rig 12",
    generatedBy: "Drilling Engineer",
    generatedOn: "May 23, 2025 08:15 PM",
    period: "May 17 – May 23, 2025",
    format: "PDF",
    size: "3.1 MB",
  },
  {
    name: "NPT Analysis Report",
    icon: "hourglass",
    type: "On Demand",
    tone: "orange",
    wellRig: "OML18-W12 / Rig 12",
    generatedBy: "Drilling Engineer",
    generatedOn: "May 23, 2025 02:45 PM",
    period: "Apr 20 – May 23, 2025",
    format: "Excel",
    size: "1.8 MB",
  },
  {
    name: "Safety Report",
    icon: "shield",
    type: "Weekly",
    tone: "red",
    wellRig: "OML18-W12 / Rig 12",
    generatedBy: "Safety Officer",
    generatedOn: "May 22, 2025 06:20 PM",
    period: "May 16 – May 22, 2025",
    format: "PDF",
    size: "2.0 MB",
  },
  {
    name: "Well Summary Report",
    icon: "file",
    type: "On Demand",
    tone: "purple",
    wellRig: "OML18-W12 / Rig 12",
    generatedBy: "Drilling Engineer",
    generatedOn: "May 21, 2025 11:10 AM",
    period: "Apr 20 – May 21, 2025",
    format: "PDF",
    size: "4.5 MB",
  },
];

/* ---- Row 3 (right): Scheduled reports ------------------------------ */
export const scheduled = {
  title: "Scheduled Reports",
  description: "Manage your automated reports",
  footer: "View All Scheduled Reports",
};

export const scheduledRows: { name: string; schedule: string; tone: Tone; icon: TemplateIcon; on: boolean }[] = [
  { name: "Daily Drilling Report", schedule: "Every day at 07:00 AM", tone: "blue", icon: "doc", on: true },
  { name: "Weekly Summary Report", schedule: "Every Monday at 08:00 AM", tone: "green", icon: "calendar", on: true },
  { name: "Safety Report", schedule: "Every Friday at 06:00 PM", tone: "red", icon: "shield", on: true },
  { name: "Monthly Cost Report", schedule: "1st of every month at 09:00 AM", tone: "teal", icon: "dollar", on: true },
];
